const mongoose = require("mongoose");

const documentChunkSchema =
  new mongoose.Schema(
    {
      // Name of the original uploaded PDF/document
      documentName: {
        type: String,
        required: true,
        index: true,
      },

      // MongoDB ID of the document record
      documentId: {
        type:
          mongoose.Schema.Types.ObjectId,
        ref: "Document",
        default: null,
      },

      // Actual text content of this chunk
      content: {
        type: String,
        required: true,
      },

      // Position of this chunk in the document
      chunkIndex: {
        type: Number,
        required: true,
      },

      // Page information if available
      pages: {
        type: mongoose.Schema.Types.Mixed,
        default: null,
      },

      // Vector generated by the embedding model
      embedding: {
        type: [Number],
        required: true,
      },

      // Additional document information
      metadata: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
    },
    {
      timestamps: true,
    }
  );

module.exports =
  mongoose.model(
    "DocumentChunk",
    documentChunkSchema
  );